import React,{useEffect,useMemo,useState}from'react';
import{Activity,CalendarDays,Check,ChevronRight,Dumbbell,Flame,Home,Plus,RotateCcw,Search,Target,TrendingUp,User,Clock,ClipboardList,X}from'lucide-react';
const days=[
{key:'MON',name:'Push Day',focus:'Chest · Shoulders · Triceps',groups:[['Chest',[['Barbell Bench Press',4,'6–8','Compound'],['Incline Dumbbell Press',3,'8–12','Compound'],['Machine Chest Press',3,'10–12','Machine'],['Cable Chest Fly',3,'12–15','Cable'],['Pec Deck Fly',2,'12–15','Machine']]],['Shoulders',[['Seated Dumbbell Shoulder Press',3,'8–12','Compound'],['Dumbbell Lateral Raise',3,'12–20','Isolation'],['Cable Lateral Raise',2,'12–15','Cable'],['Reverse Pec Deck',3,'12–15','Machine']]],['Triceps',[['Cable Triceps Pushdown',3,'10–15','Cable'],['Overhead Cable Extension',3,'10–15','Cable'],['Assisted Dips',2,'8–12','Compound']]]]},
{key:'TUE',name:'Pull Day',focus:'Back · Rear Delts · Biceps',groups:[['Back',[['Pull-Ups / Assisted Pull-Ups',3,'6–10','Compound'],['Lat Pulldown',3,'8–12','Machine'],['Barbell Row',3,'6–10','Compound'],['Chest-Supported Row',3,'8–12','Machine'],['Seated Cable Row',3,'10–12','Cable'],['Straight-Arm Pulldown',2,'12–15','Cable'],['Back Extension',2,'10–15','Bodyweight']]],['Rear Delts',[['Face Pull',3,'12–20','Cable'],['Reverse Dumbbell Fly',2,'12–15','Isolation']]],['Biceps & Forearms',[['EZ-Bar Curl',3,'8–12','Free weight'],['Incline Dumbbell Curl',3,'10–12','Free weight'],['Hammer Curl',2,'10–15','Free weight'],['Wrist Curl',2,'12–20','Isolation']]]]},
{key:'WED',name:'Leg Day A',focus:'Quads · Hamstrings · Glutes · Calves',groups:[['Quads & Glutes',[['Barbell Back Squat',4,'6–8','Compound'],['Leg Press',3,'10–12','Machine'],['Bulgarian Split Squat',3,'8–10 / leg','Free weight'],['Leg Extension',3,'12–15','Machine']]],['Hamstrings & Glutes',[['Romanian Deadlift',3,'8–10','Compound'],['Seated Leg Curl',3,'10–15','Machine'],['Hip Thrust',3,'8–12','Compound']]],['Calves & Core',[['Standing Calf Raise',4,'10–15','Machine'],['Cable Crunch',3,'12–15','Cable']]]]},
{key:'THU',name:'Active Recovery',focus:'Mobility · Walking · Recovery',groups:[['Recovery',[['Easy Walk or Cycle',1,'20–30 min','Cardio'],['Hip Mobility',1,'5–8 min','Mobility'],['Shoulder Mobility',1,'5–8 min','Mobility'],['Gentle Stretching',1,'5–10 min','Mobility']]]]},
{key:'FRI',name:'Upper Body',focus:'Chest · Back · Shoulders · Arms',groups:[['Chest & Back',[['Incline Barbell Press',3,'8–10','Compound'],['One-Arm Dumbbell Row',3,'8–12 / side','Compound'],['Machine Chest Press',2,'10–12','Machine'],['Neutral-Grip Lat Pulldown',3,'10–12','Machine']]],['Shoulders & Arms',[['Dumbbell Lateral Raise',3,'12–20','Isolation'],['Cable Face Pull',2,'12–15','Cable'],['Preacher Curl',3,'10–12','Machine'],['Rope Triceps Pushdown',3,'10–15','Cable']]]]},
{key:'SAT',name:'Leg Day B',focus:'Glutes · Hamstrings · Quads · Calves',groups:[['Posterior Chain',[['Trap-Bar Deadlift or Deadlift',3,'5–6','Compound'],['Hip Thrust',3,'8–12','Compound'],['Lying Leg Curl',3,'10–15','Machine'],['Cable Pull-Through',2,'12–15','Cable']]],['Quads & Calves',[['Front Squat or Hack Squat',3,'8–10','Compound'],['Walking Lunges',2,'10 / leg','Free weight'],['Leg Extension',2,'12–15','Machine'],['Seated Calf Raise',4,'12–20','Machine']]],['Core',[['Plank',3,'30–60 sec','Bodyweight'],['Hanging Knee Raise',3,'10–15','Bodyweight']]]]},
{key:'SUN',name:'Rest Day',focus:'Recover · Eat well · Prepare for next week',groups:[['Optional recovery',[['Leisurely Walk',1,'15–30 min','Cardio'],['Gentle Stretching',1,'5–10 min','Mobility']]]]}
];
const extras=[['Dumbbell Bench Press','Chest','Free weight'],['Decline Bench Press','Chest','Compound'],['Smith Machine Bench Press','Chest','Machine'],['Low-to-High Cable Fly','Chest','Cable'],['Push-Ups','Chest','Bodyweight'],['Arnold Press','Shoulders','Free weight'],['Machine Shoulder Press','Shoulders','Machine'],['Dumbbell Shrugs','Traps','Free weight'],['Close-Grip Bench Press','Triceps','Compound'],['Skull Crushers','Triceps','Free weight'],['Dumbbell Kickback','Triceps','Free weight'],['T-Bar Row','Back','Compound'],['Pendlay Row','Back','Compound'],['Single-Arm Cable Row','Back','Cable'],['Dumbbell Pullover','Back','Free weight'],['Rack Pull','Back','Compound'],['Barbell Curl','Biceps','Free weight'],['Cable Curl','Biceps','Cable'],['Concentration Curl','Biceps','Free weight'],['Reverse Curl','Forearms','Free weight'],['Goblet Squat','Quads','Free weight'],['Hack Squat','Quads','Machine'],['Step-Ups','Quads','Bodyweight'],['Good Morning','Hamstrings','Compound'],['Nordic Curl','Hamstrings','Bodyweight'],['Glute Bridge','Glutes','Bodyweight'],['Cable Kickback','Glutes','Cable'],['Hip Abduction Machine','Glutes','Machine'],['Donkey Calf Raise','Calves','Machine'],['Ab Wheel Rollout','Abs','Bodyweight'],['Russian Twist','Abs','Bodyweight'],['Pallof Press','Abs','Cable'],['Treadmill Walk','Cardio','Cardio'],['Stationary Bike','Cardio','Cardio'],['Elliptical','Cardio','Cardio'],['Rowing Machine','Cardio','Cardio']];
const all=days.flatMap(d=>d.groups.flatMap(g=>g[1].map(e=>({name:e[0],sets:e[1],reps:e[2],type:e[3],group:g[0],day:d.name})))).concat(extras.map(e=>({name:e[0],group:e[1],type:e[2],sets:3,reps:'8–12',day:'Exercise Library'})));
const date=()=>new Date().toLocaleDateString('en-CA');const today=()=>((new Date().getDay()+6)%7);
export default function App(){
const [page,S]=useState('Home'),[di,SD]=useState(today()),[done,D]=useState(()=>JSON.parse(localStorage.getItem('jfp-done')||'{}')),[logs,L]=useState(()=>JSON.parse(localStorage.getItem('jfp-weights')||'[]')),[weight,W]=useState(''),[query,Q]=useState(''),[filter,F]=useState('All'),[collapsed,C]=useState({}),[custom,U]=useState(()=>JSON.parse(localStorage.getItem('jfp-custom')||'[]')),[showForm,SF]=useState(false),[name,N]=useState(''),[muscle,M]=useState('Chest'),[sets,SS]=useState('3'),[reps,SR]=useState('8–12');
useEffect(()=>localStorage.setItem('jfp-done',JSON.stringify(done)),[done]);useEffect(()=>localStorage.setItem('jfp-weights',JSON.stringify(logs)),[logs]);useEffect(()=>localStorage.setItem('jfp-custom',JSON.stringify(custom)),[custom]);
const w=days[di],key=date()+'-'+w.key,checked=done[key]||[],count=w.groups.reduce((n,g)=>n+g[1].length,0),total=Object.values(done).reduce((n,a)=>n+a.length,0);
const results=useMemo(()=>all.filter(x=>(filter==='All'||x.group===filter||x.type===filter)&&x.name.toLowerCase().includes(query.toLowerCase())),[filter,query]);
function toggle(n){D(o=>({...o,[key]:(o[key]||[]).includes(n)?o[key].filter(x=>x!==n):[...(o[key]||[]),n]}))}
function addWeight(e){e.preventDefault();let v=Number(weight);if(v>=20&&v<=400){L(o=>[{kg:v,date:date()},...o].slice(0,50));W('')}}
function addCustom(e){e.preventDefault();if(name.trim()){U(o=>[{name:name.trim(),group:muscle,type:'Custom',sets,reps},...o]);N('');SF(false)}}
const nav=[['Home',Home],['Workout',Dumbbell],['Library',ClipboardList],['Progress',TrendingUp],['Profile',User]];
return <div className="app"><header><div className="logo"><Dumbbell/></div><div className="brand"><b>Johns Fit <span>Planner</span></b><small>PLAN · TRAIN · BUILD · REPEAT</small></div><button className="avatar" onClick={()=>S('Profile')}><User size={18}/></button></header><main>
{page==='Home'&&<><section className="hero"><small>● YOUR FITNESS JOURNEY</small><h1>STRONGER EVERY<br/><em>SINGLE DAY.</em></h1><p>Build muscle with a plan. Track every session. Keep moving forward.</p><div className="stats"><div><small>EXERCISES CHECKED</small><b>{total}</b></div><div><small>WEIGH-INS</small><b>{logs.length}</b></div><div><small>WEEKLY SPLIT</small><b>5 + 2</b></div></div></section><div className="heading"><div><small>LET'S GET TO WORK</small><h2>Today's session</h2></div><button onClick={()=>S('Workout')}>Full plan ›</button></div><section className="today"><div className="banner"><small>{days[today()].key} · WEEKLY SPLIT</small><div><p>{days[today()].focus}</p><h2>{days[today()].name}</h2></div></div><div className="todaybody"><span><Dumbbell size={15}/> {days[today()].groups.reduce((n,g)=>n+g[1].length,0)} exercises</span><span><Clock size={15}/> 50–75 min</span><button className="primary" onClick={()=>{SD(today());S('Workout')}}>Open workout <ChevronRight size={16}/></button></div></section><div className="heading"><div><small>YOUR ROUTINE</small><h2>This week</h2></div></div><div className="week">{days.map((d,i)=><button key={d.key} onClick={()=>{SD(i);S('Workout')}}><small>{d.key}</small><b>{d.name}</b><span>{d.groups.reduce((n,g)=>n+g[1].length,0)} moves</span></button>)}</div><aside><Flame/><div><b>Muscle-building reminder</b><p>Progress gradually, eat enough protein, sleep well, and recover between hard sessions.</p></div></aside></>}
{page==='Workout'&&<><div className="pagehead"><small>YOUR TRAINING SCHEDULE</small><h1>WEEKLY <em>PLAN.</em></h1><p>Choose a day to view exercises, sets and rep targets.</p></div><div className="dayrow">{days.map((d,i)=><button className={i===di?'chosen':''} key={d.key} onClick={()=>SD(i)}><small>{d.key}</small><b>{d.name.replace(' Day','')}</b></button>)}</div><section className="session"><div><small>DAY {di+1} OF 7</small><h2>{w.name}</h2><p>{w.focus}</p></div><strong>{Math.round(checked.length/count*100)}%</strong></section><div className="bar"><span style={{width:`${checked.length/count*100}%`}}/></div><div className="muted">{checked.length}/{count} completed <button onClick={()=>D(o=>({...o,[key]:[]}))}><RotateCcw size={13}/> Reset</button></div>{w.groups.map(g=><section className="group" key={g[0]}><button className="group-title" onClick={()=>C(o=>({...o,[g[0]]:!o[g[0]]}))}>{g[0]} <small>{g[1].length} exercises⌄</small></button>{!collapsed[g[0]]&&g[1].map(e=><button className="exercise" key={e[0]} onClick={()=>toggle(e[0])}><span className={'check '+(checked.includes(e[0])?'yes':'')}>{checked.includes(e[0])&&<Check size={14}/>}</span><span><b>{e[0]}</b><small>{e[3]} · {e[1]} sets · {e[2]} reps</small></span><ChevronRight size={15}/></button>)}</section>)}<p className="safety">Warm up first. Use controlled form and a manageable load. Stop if you feel sharp pain.</p></>}
{page==='Library'&&<><div className="pagehead"><small>EXERCISE DATABASE</small><h1>FIND YOUR <em>MOVE.</em></h1><p>Search common gym exercises by muscle group or equipment.</p></div><div className="search"><Search/><input value={query} onChange={e=>Q(e.target.value)} placeholder="Search exercises..."/>{query&&<button onClick={()=>Q('')}><X/></button>}</div><div className="filters">{['All','Chest','Back','Shoulders','Triceps','Biceps','Quads','Hamstrings','Glutes','Calves','Abs','Cardio','Machine','Cable'].map(x=><button className={filter===x?'on':''} onClick={()=>F(x)} key={x}>{x}</button>)}</div><small className="muted">{results.length} exercises in library</small>{results.map(x=><div className="libitem" key={x.name}><div><Dumbbell/></div><span><b>{x.name}</b><small>{x.group} · {x.type} · {x.sets} sets · {x.reps}</small></span></div>)}{custom.map(x=><div className="libitem" key={x.name}><div><Plus/></div><span><b>{x.name}</b><small>{x.group} · {x.sets} sets · {x.reps} reps</small></span></div>)}</>}
{page==='Progress'&&<><div className="pagehead"><small>YOUR TRAINING HISTORY</small><h1>MEASURE <em>PROGRESS.</em></h1><p>Keep a simple record of body weight and completed exercises.</p></div><div className="metrics"><div><Activity/><small>EXERCISES CHECKED</small><b>{total}</b></div><div><TrendingUp/><small>WEIGHT ENTRIES</small><b>{logs.length}</b></div></div><form className="weightform" onSubmit={addWeight}><label>Record body weight (kg)</label><div><input type="number" min="20" max="400" step=".1" placeholder="e.g. 68.5" value={weight} onChange={e=>W(e.target.value)} required/><button className="primary"><Plus size={15}/> Add</button></div></form><div className="heading"><div><small>RECENT ENTRIES</small><h2>Weight log</h2></div></div>{logs.length===0?<p className="empty">No weigh-ins yet. Add your weight above.</p>:logs.map((x,i)=><div className="weightrow" key={x.date+i}><span><CalendarDays size={15}/>{x.date}</span><b>{x.kg.toFixed(1)} kg</b></div>)}<p className="muted">Progress is saved locally on this device. Clearing app data may erase it.</p></>}
{page==='Profile'&&<><div className="pagehead"><small>YOUR FITNESS SPACE</small><h1>TRAIN WITH <em>PURPOSE.</em></h1><p>Customize your routine and keep your goals in view.</p></div><div className="profile"><div className="bigavatar"><User/></div><div><b>Johns Fit Planner</b><small>Intermediate · Muscle gain</small></div></div><div className="heading"><div><small>PERSONAL TOOLS</small><h2>Planner settings</h2></div></div><button className="setting" onClick={()=>S('Library')}><ClipboardList/><span><b>Exercise library</b><small>Browse and search exercises</small></span><ChevronRight/></button><button className="setting" onClick={()=>SF(!showForm)}><Plus/><span><b>Create custom exercise</b><small>Add a move to your personal list</small></span><ChevronRight/></button>{showForm&&<form className="customform" onSubmit={addCustom}><label>Exercise name</label><input value={name} onChange={e=>N(e.target.value)} placeholder="e.g. Cable fly" required/><label>Muscle group</label><select value={muscle} onChange={e=>M(e.target.value)}>{['Chest','Back','Shoulders','Triceps','Biceps','Quads','Hamstrings','Glutes','Calves','Abs','Cardio'].map(x=><option key={x}>{x}</option>)}</select><div className="twocol"><div><label>Sets</label><input value={sets} onChange={e=>SS(e.target.value)}/></div><div><label>Reps</label><input value={reps} onChange={e=>SR(e.target.value)}/></div></div><button className="primary">Save exercise</button></form>}<button className="setting" onClick={()=>S('Progress')}><TrendingUp/><span><b>Progress log</b><small>Weight entries and activity</small></span><ChevronRight/></button><aside><Target/><div><b>Consistency beats perfection</b><p>Adapt the plan to your equipment, recovery and experience.</p></div></aside></>}
</main><nav className="bottom">{nav.map(([label,Icon])=><button className={page===label?'active':''} key={label} onClick={()=>S(label)}><Icon size={19}/><small>{label}</small></button>)}</nav></div>}
